name: Build Android Apk
on:
  pull_request:
    branches: master

jobs:
  build:
    name: build apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
        
      - name: Install Cordova
        run: npm install -g cordova
      
      - name: Install Ionic 
        run: npm install -g @ionic/cli
        
      - name: Show current working directory and list contents
        working-directory: ./app
        run: pwd && ls
      
      - name: Install app dependencies
        working-directory: ./app
        run: npm install
      
      - name: Add Android Platform
        working-directory: ./app
        run: ionic cordova platform add android@latest
      
      - name: Build the debug apk
        working-directory: ./app
        run: ionic cordova build android
        
      - name: Generate the Android app bundle
        working-directory: .app/platform/android
        run: ./gradlew bundle
        
      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
